/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasibukualamat;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import com.mysql.cj.jdbc.PreparedStatementWrapper;
import java.io.FileWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FormAturData extends javax.swing.JFrame {

    /**
     * Creates new form FormAturData
     */
    public FormAturData() {
        initComponents();
        cleanField(); // memanggil method cleanField()
        showData(); //memanggil method showData()
    }
    
    String id;
    Connection con = Koneksi.getKoneksi();
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        inputTelp = new javax.swing.JTextField();
        inputJln = new javax.swing.JTextField();
        inputKota = new javax.swing.JTextField();
        inputProv = new javax.swing.JTextField();
        inputRelasi = new javax.swing.JComboBox<>();
        bHapus = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bUlang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu - [Atur Data Buku Alamat]");

        jPanel1.setBackground(new java.awt.Color(255, 51, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Atur Data Alamat"));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Nama Lengkap");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Nomer Telepon");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Relasi");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Jalan / Gang");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Kota / kabupaten");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Provinsi");

        inputTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTelpKeyTyped(evt);
            }
        });

        inputRelasi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inputRelasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Relasi -", "Keluarga", "Teman", "Teman Kerja", "Teman Sekolah", "Orang Penting" }));

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bSimpan.setText("Simpan (txt)");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bUlang.setText("Ulang");
        bUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUlangActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(inputNama))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(inputTelp))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(inputRelasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(inputJln))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(inputKota))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(bTambah)
                                    .addGap(18, 18, 18)
                                    .addComponent(bEdit)
                                    .addGap(18, 18, 18)
                                    .addComponent(bHapus)
                                    .addGap(18, 18, 18)
                                    .addComponent(bUlang)
                                    .addGap(18, 18, 18)
                                    .addComponent(bSimpan)
                                    .addGap(0, 64, Short.MAX_VALUE))
                                .addComponent(inputProv))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputRelasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputJln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHapus)
                    .addComponent(bTambah)
                    .addComponent(bEdit)
                    .addComponent(bSimpan)
                    .addComponent(bUlang))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Atur Data Buku Alamat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        if (inputNama.getText().isEmpty() || inputTelp.getText().isEmpty() || inputJln.getText().isEmpty() || inputKota.getText().isEmpty() || inputProv.getText().isEmpty() || inputRelasi.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Ada Data Yang Belum Diisi!!", "Gagal Menambahkan Data", 2); // untuk menampilkan pesan peringatan
        } else {
            try {
                String dbTambah = "INSERT INTO alamat VALUES (null, ?, ?, ?, ?, ?, ?);"; 
                pst = con.prepareStatement(dbTambah);
                pst.setString(1, inputNama.getText());
                pst.setString(2, inputTelp.getText());
                pst.setString(3, inputRelasi.getSelectedItem().toString());
                pst.setString(4, inputJln.getText());
                pst.setString(5, inputKota.getText());
                pst.setString(6, inputProv.getText());
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan!!", "Sukses Menambahkan Data", 1); // untuk menampilkan pesan informasi
                cleanField(); // memanggil method cleanField()
                showData(); //memanggil method showData()
            } catch (SQLException ex) {
                Logger.getLogger(FormAturData.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bTambahActionPerformed

    private void bUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUlangActionPerformed
        cleanField();
    }//GEN-LAST:event_bUlangActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        id = jTable1.getValueAt(row, 0).toString();
        
        inputNama.setText(jTable1.getValueAt(row, 1).toString());
        inputTelp.setText(jTable1.getValueAt(row, 2).toString());
        inputRelasi.setSelectedItem(jTable1.getValueAt(row, 3).toString());
        inputJln.setText(jTable1.getValueAt(row, 4).toString());
        inputKota.setText(jTable1.getValueAt(row, 5).toString());
        inputProv.setText(jTable1.getValueAt(row, 6).toString());
        bTambah.setEnabled(false);
        bEdit.setEnabled(true);
        bHapus.setEnabled(true);   
        bSimpan.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        if (inputNama.getText().isEmpty() || inputTelp.getText().isEmpty() || inputJln.getText().isEmpty() || inputKota.getText().isEmpty() || inputProv.getText().isEmpty() || inputRelasi.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Data Ada Yang Kosong, Data Yang Diubah Tidak Boleh Kosong!!", "Gagal Mengubahkan Data", 2); // untuk menampilkan pesan peringatan
        } else {
            try {
                String dbUbah = "UPDATE alamat SET nama = ?, no_telp = ?, relasi = ?, jalan = ?, kota = ?, provinsi = ? WHERE id = ?;";
                pst = con.prepareStatement(dbUbah);
                pst.setString(1, inputNama.getText());
                pst.setString(2, inputTelp.getText());
                pst.setString(3, inputRelasi.getSelectedItem().toString());
                pst.setString(4, inputJln.getText());
                pst.setString(5, inputKota.getText());
                pst.setString(6, inputProv.getText());
                pst.setString(7, id);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Data Berhasil Diedit!!", "Sukses Mengedit Data", 1); // untuk menampilkan pesan informasi
                cleanField(); // memanggil method cleanField()
                showData(); //memanggil method showData()
            } catch (SQLException ex) {
                Logger.getLogger(FormAturData.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            }
    }//GEN-LAST:event_bEditActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        if (inputNama.getText().isEmpty() || inputTelp.getText().isEmpty() || inputJln.getText().isEmpty() || inputKota.getText().isEmpty() || inputProv.getText().isEmpty() || inputRelasi.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Data Ada Yang Kosong, Data Yang Dihapus Tidak Boleh Kosong!!", "Gagal Menghapus Data", 2); // untuk menampilkan pesan peringatan
        } else {
            int confirm = JOptionPane.showConfirmDialog(null,"Hapus Data Alamat Ini?", "Konfirmasi Hapus", 0);
                
            if (confirm == 0) { // untuk jika memilih ya saat joption muncul akan menghapus datanya
                try {
                    String queryHapus = "DELETE FROM alamat WHERE id = ?;";
                    pst = con.prepareStatement(queryHapus);
                    pst.setString(1, id);
                    pst.executeUpdate();
                        
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!!", "Sukses Menghapus", 1);
                    cleanField(); // memanggil method cleanField()
                    showData(); //memanggil method showData()
                } catch (SQLException ex) {
                    Logger.getLogger(FormAturData.class.getName()).log(Level.SEVERE, null, ex);
                }            
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        if (inputNama.getText().isEmpty() || inputTelp.getText().isEmpty() || inputJln.getText().isEmpty() || inputKota.getText().isEmpty() || inputProv.getText().isEmpty() || inputRelasi.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Data Ada Yang Kosong, Data Yang Disimpan Tidak Boleh Kosong!!", "Gagal Menyimpan Data Ke Perangkat", 2); // untuk menampilkan pesan peringatan
        } else {
            StringBuilder content = new StringBuilder();
            content.append("Data Alamat Yang Disimpan :").append("\n\n");
            
            content.append("Nama Pemilik Alamat : ").append(inputNama.getText()).append("\n");
            content.append("Nomer Telepon : ").append(inputTelp.getText()).append("\n");
            content.append("Relasi : ").append(inputRelasi.getSelectedItem()).append("\n");
            content.append("Alamat : ").append(inputJln.getText()).append(", ").append(inputKota.getText()).append(", ").append(inputProv.getText()).append(". \n");
            
            
            
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Simpan Data Alamat");
            int userSelection = fileChooser.showSaveDialog(this);
            
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                try (FileWriter fileWriter = new FileWriter(fileChooser.getSelectedFile() + ".txt")) {
                    fileWriter.write(content.toString());
                    JOptionPane.showMessageDialog(this, "Data kontak berhasil disimpan ke Perangkat");
                    cleanField();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan file: " + ex.getMessage());
                    cleanField();
                }
            }
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void inputTelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTelpKeyTyped
        char c = evt.getKeyChar();
                
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        
        if (inputTelp.getText().length() >= 12) {
            JOptionPane.showMessageDialog(null, "Angka Yang Dimasukkan Harus tidak lebih dari 12!!", "Peringatan", 2);
            evt.consume();
        }
    }//GEN-LAST:event_inputTelpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAturData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAturData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAturData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAturData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAturData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUlang;
    private javax.swing.JTextField inputJln;
    private javax.swing.JTextField inputKota;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputProv;
    private javax.swing.JComboBox<String> inputRelasi;
    private javax.swing.JTextField inputTelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void cleanField() {
        inputNama.setText(""); // agar saat dijalankan semua textField kosong dan mematikan tombol edit dan hapus jika belum ada data yang dipilih
        inputTelp.setText("");
        inputJln.setText("");
        inputKota.setText("");
        inputProv.setText("");
        inputRelasi.setSelectedIndex(0);
        bTambah.setEnabled(true);
        bEdit.setEnabled(false);
        bHapus.setEnabled(false); 
        bSimpan.setEnabled(false);
    }

    private void showData() {
        try {
            String[] judul = {"ID", "Nama", "No Telepon", "Relasi", "Jalan", "Kota", "Provinsi"};
            DefaultTableModel dtm = new DefaultTableModel(null, judul);
            jTable1.setModel(dtm);
            
            String sql = "SELECT * FROM alamat";
            
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String[] data = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormAturData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
